version: '3.8'
services:
  devcontainer:
    build:
      context: BioREx-docker
      dockerfile: Dockerfile
    environment:
      - LLAMA_INDEX_CACHE_DIR=/root/.cache
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2gb
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ~/Github/bioin-401-project/data:/data:cached
    command: sleep infinity
    networks:
      - rgd-chatbot

  aioner:
    build:
      context: AIONER-docker
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2gb
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ~/Github/bioin-401-project/data:/data:cached
    command: sleep infinity
    networks:
      - rgd-chatbot

  biorex:
    build:
      context: BioREx-docker
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2gb
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ~/Github/bioin-401-project/data:/data:cached
    command: sleep infinity
    networks:
      - rgd-chatbot

  gnorm2:
    build:
      context: GNorm2-docker
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2gb
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ~/Github/bioin-401-project/data:/data:cached
    command: sleep infinity
    networks:
      - rgd-chatbot

  taggerone:
    build:
      context: TaggerOne-PubTator3-docker
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2gb
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ~/Github/bioin-401-project/data:/data:cached
    command: sleep infinity
    networks:
      - rgd-chatbot

networks:
  rgd-chatbot:
    external: true
    name: rgd-chatbot

volumes:
  ollama:
